- hosts: localhost
  connection: local


  tasks:
   - vmware_cluster:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ item.datacenter }}"
      cluster_name: "{{ item.cluster }}"
      state: present
      validate_certs: false
      
     with_items: "{{ cluster }}"

