- hosts: localhost
  connection: local


  tasks:
   - vmware_cluster:
      hostname: 192.168.49.51
      username: administrator@vsphere.local
      password: Shinjb#826
      datacenter_name: "{{ item.datacenter }}"
      cluster_name: "{{ item.cluster }}"
      state: present
      validate_certs: false
      
     with_items: "{{ cluster }}"

