- hosts: localhost
  connection: local

  include_vars:
   file: localhost.yml

  tasks:
   - vmware_datacenter:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ item }}"
      state: present
      validate_certs: false
     with_items: "{{ datacenter }}"
