- hosts: localhost
  connection: local

#  vars: 
#   - vcenter: item.center
#   - with_items:
#     center: {{ asdf }}

  tasks:
   - vmware_datacenter:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ item }}"
      state: present
      validate_certs: false
     with_items: "{{ datacenter }}"

