
- hosts: localhost
  connection: local
  tasks:
   - vmware_datacenter:
      hostname: 192.168.49.51
      username: administrator@vsphere.local
      password: Shinjb#826
      datacenter_name: "datacenter_1"
      state: present
      validate_certs: false
