- hosts: localhost
  connection: local


  tasks:
   - vmware_host:
      hostname: 192.168.49.51
      username: administrator@vsphere.local
      password: Shinjb#826
      datacenter_name: "{{ item.datacenter }}"
      switch_namee: "{{ item.switch }}"
      esxi_hostname: "{{ item.esxi }}"
      mtu: 9000
      uplink_quantity: 4


      esxi_username: "{{ item.username }}"
      esxi_password: "{{ item.password }}"
      state: present
      validate_certs: false
      
     with_items: "{{ dvswitch}}"


