- hosts: localhost
  connection: local
  tasks:
   - vmware_dvswitch:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ item.datacenter }}"
      switch_name: "{{ item.switch }}"
      mtu: "{{ item.mtu }}"
      uplink_quantity: "{{ item.uplink }}"
      discovery_proto: "{{ item.proto }}"
      discovery_operation: "{{ item.operation }}"
      state: present
      validate_certs: false
     with_items: "{{ dvswitch }}"


