- hosts: localhost
  connection: local


  tasks:
   - vmware_dvs_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      portgroup_name: "{{ item.portgroup }}"
      switch_name: "{{ item.switch }}"
      vlan_id: "{{ item.vlan }}"
      num_ports: "{{ item.port }}"
      portgroup_type: "{{ item.type }}"      



      state: present
      validate_certs: false
      
     with_items: "{{ portgroup }}"


