vcenter_hostname: 192.168.49.51
vcenter_username: administrator@vsphere.local
vcenter_password: Shinjb#826

esxi_username: root
esxi_password: tlswnsqja

datacenter_name:
  - "ans_datacenter_1"


esxi_host: 
  - 192.168.49.100
  - 192.168.49.102

datacenter:
  - "{{ datacenter_name }}"


cluster:
  - {datacenter: "{{ datacenter_name }}" , cluster: "ans_mgmt"}
  - {datacenter: "{{ datacenter_name }}" , cluster: "ans_compute"}
  - {datacenter: "{{ datacenter_name }}" , cluster: "ans_edge"}



hosts:
  - {datacenter: "ans_datacenter_1" , cluster: "ans_mgmt" , esxi: 192.168.49.102}

hosts1:
  - {cluster: "ans_mgmt" , esxi: 192.168.49.102}

dvswitch:
  - {datacenter: "{{ datacenter_name }}" , switch: "ans_switch1" , mtu: "9000" , uplink: "4" , proto: lldp , operation: "both" } 

dvs_host:
  - { host: 192.168.49.100 , switch: "ans_switch1" , vnic1: "vmnic1" , vnic2: "vmnic2" }


portgroup:
  - {portgroup: "ans_pg1" , switch: "ans_switch1" , vlan: "101" , port: "120" , type: "earlyBinding" }
  - {portgroup: "ans_pg2" , switch: "ans_switch1" , vlan: "102" , port: "120" , type: "earlyBinding" }
  - {portgroup: "ans_pg3" , switch: "ans_switch1" , vlan: "103" , port: "120" , type: "earlyBinding" }
  - {portgroup: "ans_pg4" , switch: "ans_switch1" , vlan: "104" , port: "120" , type: "earlyBinding" }
  - {portgroup: "ans_pg5" , switch: "ans_switch1" , vlan: "105" , port: "120" , type: "earlyBinding" }
  - {portgroup: "ans_pg6" , switch: "ans_switch1" , vlan: "106" , port: "120" , type: "earlyBinding" }







